technologies:
  
  - name: 'Swift'
    projects:
      - name: itsme
        description: null
        url: null
        tags: null

      - name: Vulture
        description: null
        url: null
        tags: null

      - name: Aviobook
        description: null
        url: null
        tags: null

      - name: TruliUs
        description: null
        url: null
        tags: null

      - name: Telenet Yugo
        description: null
        url: null
        tags: null

      - name: Horizon Go
        description: null
        url: null
        tags: null

      - name: 22
        description: null
        url: null
        tags: null

      - name: Philips Hue PoS
        description: null
        url: null
        tags: null

      - name: SkySight Wave
        description: null
        url: null
        tags: null

      - name: Soaring Book
        description: null
        url: null
        tags: null

      - name: GPX Reader
        description: null
        url: null
        tags: null

      - name: Monizze
        description: null
        url: null
        tags: null

      - name: Track
        description: null
        url: null
        tags: null
      
  - name: 'SwiftUI'
    projects:
      - name: Expendr
        description: null
        url: null
        tags: null

      - name: Pace Up
        description: null
        url: null
        tags: null

  - name: 'Objective-C'
    projects:
      - name: Telenet Yelo
        description: null
        url: null
        tags: null

      - name: Geluidshuis
        description: null
        url: null
        tags: null

      - name: Isabel
        description: null
        url: null
        tags: null

      - name: Connective
        description: null
        url: null
        tags: null

      - name: Belins
        description: null
        url: null
        tags: null

      - name: Niko
        description: null
        url: null
        tags: null

      - name: Bolero
        description: null
        url: null
        tags: null

      - name: 1Limburg
        description: null
        url: null
        tags: null

      - name: Wie is De Mol
        description: null
        url: null
        tags: null

      - name: Eggy
        description: null
        url: null
        tags: null

      - name: Snabb
        description: null
        url: null
        tags: null

      - name: Car Sharing
        description: null
        url: null
        tags: null

      - name: Luan
        description: null
        url: null
        tags: null

      - name: Courir
        description: null
        url: null
        tags: null

      - name: Pomidor
        description: null
        url: null
        tags: null

      - name: Report
        description: null
        url: null
        tags: null

      - name: FaceTeam
        description: null
        url: null
        tags: null

      - name: Huvepharma
        description: null
        url: null
        tags: null

      - name: Periodica
        description: null
        url: null
        tags: null

      - name: Twunch
        description: null
        url: null
        tags: null

      - name: Fleetexpert
        description: null
        url: null
        tags: null

      - name: Besix
        description: null
        url: null
        tags: null

      - name: Factura
        description: null
        url: null
        tags: null

      - name: Pivot
        description: null
        url: null
        tags: null

      - name: Punch
        description: null
        url: null
        tags: null

      - name: Marvin Gaye Tour
        description: null
        url: null
        tags: null

      - name: DSX
        description: null
        url: null
        tags: null

      - name: IGC Reader
        description: null
        url: null
        tags: null

      - name: Spoty
        description: null
        url: null
        tags: null

      - name: RASP
        description: null
        url: null
        tags: null

      - name: 1am
        description: null
        url: null
        tags: null

  - name: Sinatra
    projects:
      - name: Fousa.be
        description: null
        url: null
        tags: null

      - name: Vulture
        description: null
        url: null
        tags: null

      - name: RASP
        description: null
        url: null
        tags: null

  - name: Ruby on Rails
    projects:
      - name: Soaring Book
        description: null
        url: null
        tags: null

      - name: Translations
        description: null
        url: null
        tags: null

      - name: M HKA
        description: null
        url: null
        tags: null

      - name: School of Arts
        description: null
        url: null
        tags: null

      - name: Fleetexpert
        description: null
        url: null
        tags: null

      - name: RHEA
        description: null
        url: null
        tags: null

      - name: Menerga
        description: null
        url: null
        tags: null

      - name: Validpat
        description: null
        url: null
        tags: null

      - name: Biegel
        description: null
        url: null
        tags: null