technologies:
  
  - name: 'Swift'
    projects:
      - name: itsme
        description: null
        url: null
        tags: null

      - name: Vulture
        description: null
        url: null
        tags: null

      - name: Aviobook
        description: null
        url: null
        tags: null

      - name: TruliUs
        description: null
        url: null
        tags: null

      - name: Telenet Yugo
        description: null
        url: null
        tags: null

      - name: Horizon Go
        description: null
        url: null
        tags: null

      - name: 22
        description: null
        url: null
        tags: null

      - name: Philips Hue PoS
        description: null
        url: null
        tags: null

      - name: SkySight Wave
        description: null
        url: null
        tags: null

      - name: Soaring Book
        description: null
        url: null
        tags: null

      - name: GPX Reader
        description: null
        url: null
        tags: null

      - name: Monizze
        description: null
        url: null
        tags: null

      - name: Track
        description: null
        url: null
        tags: null
      
  - name: 'SwiftUI'
    projects:
      - name: Expendr
        description: null
        url: null
        tags: null

      - name: Pace Up
        description: null
        url: null
        tags: null

  - name: 'Objective-C'
    projects:
      - name: Telenet Yelo
        description: null
        url: null
        tags: null

      - name: Geluidshuis
        description: null
        url: null
        tags: null

      - name: Isabel
        description: null
        url: null
        tags: null

      - name: Connective
        description: null
        url: null
        tags: null

      - name: Belins
        description: null
        url: null
        tags: null

      - name: Niko
        description: null
        url: null
        tags: null

      - name: Bolero
        description: null
        url: null
        tags: null

      - name: 1Limburg
        description: null
        url: null
        tags: null

      - name: Wie is De Mol
        description: null
        url: null
        tags: null

      - name: Eggy
        description: null
        url: null
        tags: null

      - name: Snabb
        description: null
        url: null
        tags: null

      - name: Car Sharing
        description: null
        url: null
        tags: null

      - name: Luan
        description: null
        url: null
        tags: null

      - name: Courir
        description: null
        url: null
        tags: null

      - name: Pomidor
        description: null
        url: null
        tags: null

      - name: Report
        description: null
        url: null
        tags: null

      - name: Questionnaires
        description: null
        url: null
        tags: null
      
      - name: Patient
        description: null
        url: null
        tags: null

      - name: Signup
        description: null
        url: null
        tags: null
      
      - name: Safety Surgery Checklist
        description: null
        url: null
        tags: null

      - name: FaceTeam
        description: null
        url: null
        tags: null

      - name: Huvepharma
        description: null
        url: null
        tags: null

      - name: Periodica
        description: null
        url: null
        tags: null

      - name: Twunch
        description: null
        url: null
        tags: null

      - name: Fleetexpert
        description: null
        url: null
        tags: null

      - name: Besix
        description: null
        url: null
        tags: null

      - name: Factura
        description: null
        url: null
        tags: null

      - name: Pivot
        description: null
        url: null
        tags: null

      - name: Punch
        description: null
        url: null
        tags: null

      - name: Marvin Gaye Tour
        description: null
        url: null
        tags: null

      - name: DSX
        description: null
        url: null
        tags: null

      - name: IGC Reader
        description: null
        url: null
        tags: null

      - name: Spoty
        description: null
        url: null
        tags: null

      - name: RASP
        description: null
        url: null
        tags: null

      - name: 1am
        description: null
        url: null
        tags: null

  - name: Sinatra
    projects:
      - name: Fousa.be
        description: null
        url: null
        tags: null

      - name: Vulture
        description: null
        url: null
        tags: null

      - name: RASP
        description: null
        url: null
        tags: null

  - name: Ruby on Rails
    projects:
      - name: Soaring Book
        description: 'Manage the organization of a gliding club completely online. This website supports the iPad application that was used on the airfield. And sends invoices to all the pilots afterward.'
        url: 'https://soaringbook.com'
        tags: 'EBBT'

      - name: Translations
        description: 'A supporting web application to manage all the different localisations used in mobile applications. The data was accessible through an API and a supporting gem.'
        url: 'https://translations.icapps.com'
        tags: 'icapps'

      - name: M HKA
        description: 'Manage the resources and support for the museum of contemporary art in Antwerp during its day to day business with this administrative website.'
        url: null
        tags: '10to1'

      - name: Het Spiegelpaleis
        description: 'Participate in the live quiz broadcasted on prime-time on national tv in Belgium. I had the chance of working on this very challenging product with an incredible team at the University of Ghent.'
        url: null
        tags: '10to1'

      - name: Fleetexpert
        description: 'Get an overview of all the cars, with their damages, that are checked with the Fleetexpert iPad application by the experts. It also provides the application with the required content for the app.'
        url: null
        tags: '10to1'

      - name: Menerga
        description: 'Manage the stock and supplies needed to make it possible to plan the assignment in the energy industry as well as possible. We connected with external services for a more up-to-date overview of the current stock.'
        url: null
        tags: '10to1'

      - name: Validpat
        description: 'An administrative website to better support administrative services for IP Attorneys. The development process used here was behavior-driven development, which was quite a challenge, but a lot of fun.'
        url: null
        tags: 'Belighted'

      - name: Biegel
        description: 'A handy website that translates commonly used words from the Limburg region to an understandable format for the rest of Belgium. The website participated in a product development competition.'
        url: null
        tags: 'Fousa'
        
  - name: PHP
    projects:
      - name: RHEA
        description: 'The public website with information about the research studies on gender, diversity, and intersectionality that was done at the Vrije Universiteit Brussel.'
        url: null
        tags: 'Fousa'