text:
  developer: 'I consider myself a passionate <strong>iOS developer</strong>. As a professional developer, I work on some nifty applications for the best clients. And when I have some time left, I try to create and sell my apps on the App Store.'
  gliding: "When I'm not writing code, you'll probably find me in the sky looking for thermals in my glider."

apps:
  - name: 'itsme'
    image: 'itsme'
    url: 'https://www.itsme-id.com'

  - name: 'Aviobook'
    image: 'Aviobook'
    url: 'https://aviobook.aero'

  - name: 'Vulture'
    image: 'Vulture'
    url: 'https://vulture.aero'

  - name: 'Telenet Flow'
    image: 'TelenetFlow'
    url: 'https://www2.telenet.be/residential/nl/producten/telenet-tv/flow'

  - name: 'Horizon Go'  
    image: 'HorizonGo'  
    url: 'https://apps.apple.com/sk/app/horizon-tv-app/id1456233801'
  
  - name: 'Soaring Book'
    image: 'SoaringBook'
    url: 'https://apps.apple.com/nl/app/soaring-book-runway/id1422856598'

  - name: 'Pace Up'     
    image: 'PaceUp'     
    url: 'http://paceup.fousa.be'

  - name: 'Bolero'
    image: 'Bolero'     
    url: 'https://www.bolero.be/nl/platformen/mobile'

  - name: 'PoS'
    image: 'PoS'        
    url: 'https://apps.apple.com/us/app/philips-hue-in-store-app/id1191767292'

  - name: 'Track'       
    image: 'Track'      
    url: 'https://itunes.apple.com/us/app/track/id1197989851?ls=1&mt=8'

  - name: 'TruliUs'     
    image: 'TruliUs'    
    url: 'https://www.trulius.be'

  - name: 'RASP'        
    image: 'RASP'       
    url: 'https://apps.apple.com/us/app/rasp/id426040634#'
